version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: laravel-web
        ports:
            - 8080:80
        volumes:
            - .:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: laravel-db
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lnn
            MYSQL_USER: lnn
            MYSQL_PASSWORD: lnn
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    db_data:
